/*
 * This file is generated by jOOQ.
 */
package dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema1.tables.references


import dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema1.tables.Schema1Table1
import dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema1.tables.Schema1Table2



/**
 * The table <code>schema1.schema1_table1</code>.
 */
val SCHEMA1_TABLE1: Schema1Table1 = Schema1Table1.SCHEMA1_TABLE1

/**
 * The table <code>schema1.schema1_table2</code>.
 */
val SCHEMA1_TABLE2: Schema1Table2 = Schema1Table2.SCHEMA1_TABLE2
