/*
 * This file is generated by jOOQ.
 */
package dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema3.tables


import dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema3.Schema3
import dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema3.tables.records.Schema3Table1Record

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Schema3Table1(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Schema3Table1Record>?,
    parentPath: InverseForeignKey<out Record, Schema3Table1Record>?,
    aliased: Table<Schema3Table1Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<Schema3Table1Record>(
    alias,
    Schema3.SCHEMA3,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>schema3.schema3_table1</code>
         */
        val SCHEMA3_TABLE1: Schema3Table1 = Schema3Table1()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Schema3Table1Record> = Schema3Table1Record::class.java

    /**
     * The column <code>schema3.schema3_table1.id</code>.
     */
    val ID: TableField<Schema3Table1Record, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    private constructor(alias: Name, aliased: Table<Schema3Table1Record>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Schema3Table1Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Schema3Table1Record>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>schema3.schema3_table1</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>schema3.schema3_table1</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>schema3.schema3_table1</code> table reference
     */
    constructor(): this(DSL.name("schema3_table1"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Schema3.SCHEMA3
    override fun getIdentity(): Identity<Schema3Table1Record, Int?> = super.getIdentity() as Identity<Schema3Table1Record, Int?>
    override fun `as`(alias: String): Schema3Table1 = Schema3Table1(DSL.name(alias), this)
    override fun `as`(alias: Name): Schema3Table1 = Schema3Table1(alias, this)
    override fun `as`(alias: Table<*>): Schema3Table1 = Schema3Table1(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Schema3Table1 = Schema3Table1(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Schema3Table1 = Schema3Table1(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Schema3Table1 = Schema3Table1(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Schema3Table1 = Schema3Table1(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Schema3Table1 = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Schema3Table1 = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Schema3Table1 = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Schema3Table1 = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Schema3Table1 = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Schema3Table1 = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Schema3Table1 = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Schema3Table1 = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Schema3Table1 = where(DSL.notExists(select))
}
