/*
 * This file is generated by jOOQ.
 */
package dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema3.tables.records


import dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema3.tables.Schema3Table1

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Schema3Table1Record() : TableRecordImpl<Schema3Table1Record>(Schema3Table1.SCHEMA3_TABLE1) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    /**
     * Create a detached, initialised Schema3Table1Record
     */
    constructor(id: Int? = null): this() {
        this.id = id
        resetChangedOnNotNull()
    }
}
