services:
  postgres:
    image: postgres:15.12-alpine
    container_name: try-flyway-with-postgres-multi-schemas
    restart: always
    environment:
      POSTGRES_USER: akkinoc
      POSTGRES_PASSWORD: akkinoc-pw
      POSTGRES_DB: akkinoc-db
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: Asia/Tokyo
    ports:
      - 15432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
