/*
 * This file is generated by jOOQ.
 */
package dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema2.tables.references


import dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema2.tables.Schema2Table1
import dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema2.tables.Schema2Table2



/**
 * The table <code>schema2.schema2_table1</code>.
 */
val SCHEMA2_TABLE1: Schema2Table1 = Schema2Table1.SCHEMA2_TABLE1

/**
 * The table <code>schema2.schema2_table2</code>.
 */
val SCHEMA2_TABLE2: Schema2Table2 = Schema2Table2.SCHEMA2_TABLE2
