/*
 * This file is generated by jOOQ.
 */
package dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema3.tables.references


import dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema3.tables.Schema3Table1
import dev.akkinoc.try_flyway_with_postgres_multi_schemas.schema3.tables.Schema3Table2



/**
 * The table <code>schema3.schema3_table1</code>.
 */
val SCHEMA3_TABLE1: Schema3Table1 = Schema3Table1.SCHEMA3_TABLE1

/**
 * The table <code>schema3.schema3_table2</code>.
 */
val SCHEMA3_TABLE2: Schema3Table2 = Schema3Table2.SCHEMA3_TABLE2
